.\" The man page for the kimsay command
.Dd March 2, 2026
.Dt kimsay 6
.Os
.Sh NAME
.Nm kimsay
.Nd Get some of the wisdom of Precinct 57's best liutenant or make him speak your own.
.Sh SYNOPSIS
.Nm
.Op Fl rFn
.Op Fl f Ar artFile
.Op Fl w Ar WRAP
.Op Fl g Ar GAP
.Op Ar TEXT...
.Sh DESCRIPTION
.Nm Kimsay
prints an ASCII art portrait of Liutenant Kim Kitsuragi followed by some text in the in-game dialog format (unless
.Fl n
is provided).
If no arguments are provided it reads from standard input until EOF. Otherwise it concatenates the provided 
.Ar TEXTs
, separated by a space.


If
.Fl r
is provided,
.Ar TEXTs
are ignored and random in-game dialog is used instead.


The portrait is surrounded by a solid frame unless
.Fl F
is provided.


The formatted text is word-wrapped at 42 characters by default. If
.Fl w
is provided, the text is wrapped at
.Ar WRAP
characters instead.


The default gap between the portrait and the text is 2 characters wide. The
.Fl g
flag changes this width to
.Ar GAP
characters instead.


The resulting text and the portrait are printed to standard output side by side, separated by a 2-wide padding of spaces.


Use
.Fl f
to make
.Ar artFile
be the source of the portrait instead of the default one.

.Sh FILES
.Bl -tag
.It Pa /usr/share/kimsay/portraits
Contains the default ASCII art files.
.It Pa /usr/share/kimsay/dialog
Contains the archive with the game's dialog in json format.
.El
.Sh AUTHOR
Written by
.An Naft
(IcaroJam@github.com).
.Sh CONTRIBUTING
Any sugestions, contributions or bug reports may be submitted to the project's repository:
.Lk github.com/IcaroJam/kimsay
.Sh COPYRIGHT
All of Disco Elysium's dialog lines and the original art of the portraits, as well as the characters depicted in said art, are property of their respective owners and authors.
.Sh SEE ALSO
.Xr cowsay 6